spring:
  application:
    name: config
  profiles:
    active: native
  output:
    ansi:
      enabled: ALWAYS
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config